[package]
name = "axum_session_redispool"
version = "0.6.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "📝 RedisPool Database layer for axum_session."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_session_redispool"
keywords = ["Axum", "Tower", "Redis", "Session"]
repository = "https://github.com/AscendingCreations/AxumSession"

[features]
redis-clusterdb = ["redis_pool/cluster", "redis/cluster-async"]

[dependencies]
async-trait.workspace = true
redis = { version = "0.32.5", features = [
    "aio",
    "tokio-comp",
] }
axum_session.workspace = true

[dependencies.redis_pool]
#git = "https://github.com/AscendingCreations/RedisPool"
#rev = "f2324c1"
#path = "../redispool/"
version = "0.9.0"